### ISSUE TITLE
PortAudio and QT dependancy during installation

### ISSUE THREAD

**Issue by RF5** [sigmedia/sp1ny#9]
The installation on linux seems to fail without the binary portaudio and QT dependency. Is there anyway to remove this non-python dependency or make it optional? Alternatively, perhaps indicate on the readme that PortAudio and QT should be manually installed before installing sp1ny?

Cool project btw! Hoping for a standalone or one-package install method as the repo matures :)

**Comment by seblemaguer** [comment]
Hello,

Qt is necessary as the whole application relies on it. For the PortAudio part, it remains a bit unclear. I will definitely modify the README to document this. Until then I leave this issue open.

Thanks for the report :)

**Comment by RF5** [comment]
Thank you! Feel free to close once README is updated :)
